
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[370] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  110,  108,  106,  107,  105,   84,
      108,  108,   90,   83,  108,   78,   79,   88,   87,   75,
       86,   82,   89,   41,   40,   76,   72,   91,   77,   92,
       95,   96,   96,   80,  108,   81,   93,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   73,   94,   74,   85,  100,  109,   98,    3,
        3,    3,    5,    6,  102,  104,  104,  103,   71,    0,
       49,    0,    0,    0,    0,   57,   74,   66,   58,    0,
        0,   55,   63,   53,   64,   54,   65,    0,   44,    1,

        4,   56,   45,   41,    0,    0,   41,   41,    0,   41,
       40,   40,   40,   40,   81,   73,   80,   62,   68,   70,
       69,   61,   96,    0,    0,    0,    0,    0,   59,   96,
       96,   96,   96,   96,   96,   14,   96,   96,   96,   96,
       96,   96,   22,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   60,   67,  100,   98,    3,
        3,    2,  102,  104,  104,  103,   49,    0,    0,    0,
        0,    0,    0,   42,    0,    0,   50,    0,   44,    0,
       45,    0,   43,   41,   41,   41,   41,    0,   39,   40,
       40,   40,   40,   52,   51,    0,    0,    0,    0,   96,

       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       20,   96,   23,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,    0,    0,
        0,    0,    0,    0,    0,   44,    0,   45,   43,   41,
        0,    0,   39,    0,   39,   39,   40,    0,    0,    0,
        0,    7,   96,    9,   10,   96,   96,   96,   96,   16,
       17,   96,   96,   21,   24,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   36,   96,   96,    0,
        0,    0,    0,    0,    0,    0,    0,   39,   39,    0,
       46,   39,   39,    0,    0,    0,    0,    8,   11,   96,

       96,   96,   96,   19,   96,   96,   27,   96,   96,   96,
       96,   96,   96,   34,   96,   96,   38,    0,    0,    0,
       47,    0,   48,   46,   39,    0,    0,    0,   96,   96,
       96,   15,   18,   96,   26,   28,   29,   30,   31,   32,
       96,   96,   96,    0,    0,   47,   48,    0,    0,   96,
       13,   96,   33,   96,   96,  101,    0,    0,    0,   12,
       25,   35,   37,    0,   97,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   30,   30,   30,   31,   32,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   35,
       33,   33,   33,   33,   36,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   33,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    2,    3,    1,    4,    1,    5,    1,    1,    1,
        6,    1,    1,    7,    1,    1,    1,    8,    1,    9,
        9,   10,   10,    1,    1,    1,    1,    1,   11,   10,
       10,   10,   12,   12,   12,   12,   12,    1,   13,    1,
        1,    9,    9,   10,   10,   10,    9,   12,   12,   12,
       12,   12,   12,   13,   12,   12,   13,   12,   13,   12,
       13,   12,   13,   12,   12,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[412] =
    {   0,
        0,    0,   68,   70,   76,   78,   73,   79,  967,  966,
       84,   86,   92,   96,  968,  971,  971,  971,  971,  940,
       67,   98,   77,   80,  927,  971,  971,  938,   69,  971,
       85,   96,   96,  131,  177,  936,  971,  100,  936,   93,
      971,  923,  118,  971,   72,  971,  934,   95,   83,   89,
       91,  106,  111,  117,  131,  120,   96,  143,   72,  179,
      125,  122,  971,  106,  971,  971,    0,  971,    0,  957,
      956,  939,  971,  971,    0,    0,  201,  971,  971,  140,
      212,  167,  205,  911,  902,  971,  971,  971,  971,  170,
      200,  971,  971,  971,  971,  971,  971,  937,  222,  971,

      971,  971,  239,  159,  218,  260,  191,  200,  936,  240,
        0,  253,  213,  242,  971,  971,  971,  926,  971,  971,
      971,  925,  912,  230,  219,  911,    0,    0,  971,  173,
      185,  240,  254,  135,  137,  228,  245,  256,  258,  260,
      262,  265,  910,  266,  267,  270,  268,  272,  288,  283,
      275,  301,  289,  296,  293,  971,  971,    0,    0,  945,
      944,  971,    0,    0,  339,  971,  347,  939,  331,  348,
        0,  898,  900,  971,  345,    0,  971,  355,  971,  371,
      971,  337,  376,  274,  971,  909,  890,    0,  377,  276,
      971,  907,  888,  971,  971,    0,    0,    0,    0,  324,

      322,  189,  323,  343,  332,  346,  370,  351,  375,  361,
      900,  367,  899,  376,  380,  366,  378,  386,  381,  379,
      392,  395,  393,  402,  397,  328,  403,  404,  439,  472,
      887,  830,  442,  509,  428,  453,  444,  476,  971,  971,
      426,  433,  452,  542,  438,  473,  971,    0,    0,    0,
        0,  841,  419,  839,  838,  432,  405,  441,  474,  834,
      832,  467,  468,  830,  829,  503,  510,  499,  438,  482,
      495,  527,  529,  505,  521,  530,  816,  531,  497,  540,
        0,  789,  781,  535,    0,  565,  574,  540,  971,  581,
      585,  799,  766,    0,    0,    0,    0,  777,  776,  538,

      483,  570,  544,  766,  554,  545,  764,  573,  575,  571,
      572,  581,  582,  763,  584,  585,  759,  742,  740,  619,
      623,  627,  631,  971,  971,    0,    0,    0,  733,  617,
      620,  651,  649,  587,  633,  632,  628,  586,  542,  533,
      619,  588,  621,  659,  437,  971,  971,    0,    0,  590,
      430,  623,  287,  629,  630,  679,  680,    0,    0,  218,
      102,  100,   53,  684,  971,    0,    0,    0,  971,  691,
      704,  717,  730,  743,  756,  769,  782,  787,  800,  813,
      826,  839,  852,  861,  870,  876,  878,  880,  882,  884,
      886,  888,  890,  892,  894,  896,  898,  900,  902,  904,

      906,  908,  910,  912,  914,  916,  918,  920,  922,  924,
      926
    } ;

static yyconst flex_int16_t yy_def[412] =
    {   0,
      369,    1,  370,  370,  371,  371,  372,  372,  373,  373,
      374,  374,  375,  375,  369,  369,  369,  369,  369,  369,
      376,  369,  369,  369,  377,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  378,  378,  369,  369,  369,  369,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  369,  369,  369,  369,  379,  369,  380,  381,
      381,  369,  369,  369,  382,  383,  383,  369,  369,  376,
      369,  384,  369,  369,  369,  369,  369,  369,  369,  377,
      385,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,   34,  369,  369,  369,  369,  386,  369,
       35,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  378,  369,  376,  377,  387,  388,  369,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  369,  369,  379,  380,  381,
      381,  369,  382,  383,  383,  369,  369,  369,  369,  376,
      389,  369,  369,  369,  377,  390,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  391,  386,  369,
      369,  369,  369,  369,  369,  392,  393,  394,  395,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  376,  376,
      369,  369,  377,  377,  369,  369,  369,  369,  369,  369,
      391,  391,  369,  369,  369,  369,  369,  396,  397,  398,
      399,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  376,
      230,  369,  369,  377,  234,  369,  369,  369,  369,  369,
      369,  369,  369,  400,  401,  402,  403,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  369,  369,  369,
      369,  369,  369,  369,  369,  404,  405,  406,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  369,  369,  369,  369,  407,  408,  378,
      378,  378,  378,  378,  378,  369,  369,  409,  410,  378,
      378,  378,  378,  369,  369,  411,  403,  405,    0,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369
    } ;

static yyconst flex_int16_t yy_nxt[1041] =
    {   0,
       16,   17,   18,   16,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   35,   35,   36,   37,   38,   39,   40,   41,   42,
       42,   42,   42,   43,   42,   43,   42,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   42,   55,
       42,   56,   42,   42,   42,   42,   57,   58,   59,   60,
       61,   62,   42,   42,   42,   63,   64,   65,   66,   68,
       68,   68,   68,   81,   68,   71,   68,   68,   68,   68,
       68,   71,   68,   93,   68,   68,   72,   68,   68,   88,
       68,  124,   72,   77,   78,   94,   77,   77,   78,   83,

       77,   95,   83,   86,   87,   82,   89,  127,  116,  100,
      124,   96,   97,   98,  101,   99,   99,   99,   99,  121,
      122,  124,  102,  117,  125,  118,  119,  124,  126,  124,
      132,  128,  156,  124,  124,  151,  135,  133,  124,  131,
      124,  146,   84,  134,  124,  136,   81,   85,  103,  124,
      104,  104,  105,  105,  130,  124,  124,  137,  124,  138,
      124,  106,  140,  124,  107,  141,  108,  109,  139,  124,
      155,  142,  157,  124,  145,  124,  106,  143,   82,  154,
      174,  124,  110,  205,  144,  125,  170,  170,  204,  126,
      108,  147,  148,  109,  103,  369,  111,  111,  111,  111,

      152,  149,  165,  166,  150,  165,   83,  106,   91,   83,
      112,  124,  113,  167,  167,  167,  167,  124,  125,  175,
      175,  369,  106,  124,  184,   81,  185,  124,  114,  171,
      201,  200,  153,  186,  254,  103,  113,  105,  105,  105,
      105,   99,   99,   99,   99,  168,  192,  168,  106,   84,
      185,  187,  178,  179,   85,  179,  124,   82,   99,   99,
       99,   99,  176,  106,  193,  196,  124,  178,  179,  180,
      181,  169,  181,  179,  182,  185,  182,  191,  124,  183,
      183,  183,  183,  124,  180,  181,  190,  206,  191,  197,
      181,  184,  124,  190,  124,  203,  124,  202,  124,  185,

      124,  191,  207,  124,  124,  124,  124,  125,  124,  185,
      124,  191,  191,  124,  210,  208,  209,  215,  211,  218,
      214,  124,  217,  212,  213,  124,  124,  124,  216,  220,
      223,  124,  222,  185,  124,  191,  219,  125,  224,  124,
      165,  166,  228,  165,  221,  226,  225,  227,  167,  167,
      167,  167,  168,  125,   81,  174,  183,  183,  183,  183,
      124,  124,  124,  253,  233,  233,  124,  229,  229,  235,
      124,  235,  277,  258,  236,  236,  236,  236,  252,  255,
      168,  124,  168,   91,  124,  237,   82,  237,  259,  124,
      238,  238,  238,  238,  242,  183,  183,  183,  183,  124,

      256,  257,  263,  261,  124,  124,  169,  239,  124,  239,
      243,  244,  245,  124,  124,  260,  124,  124,  124,  124,
      262,  264,  239,  265,  124,  267,  270,  239,  246,  266,
      124,  124,  244,  124,  268,  124,  245,  271,  274,  269,
      124,  124,  124,  124,  278,   81,  276,  236,  236,  236,
      236,  272,  174,  273,  300,  279,  275,  124,  280,  280,
      286,  284,  284,  238,  238,  238,  238,  287,  124,  298,
      124,  292,  236,  236,  236,  236,  124,   82,   81,  124,
       91,  286,  357,  308,  179,  288,  179,  289,  287,  293,
      299,  281,  281,  281,  281,  238,  238,  238,  238,  179,

      301,  281,  281,  281,  179,  124,  124,  181,  289,  181,
       82,  289,  124,  281,  281,  281,  281,  281,  281,  174,
      124,  124,  181,  303,  288,  302,  304,  181,  285,  285,
      285,  285,  289,  124,  331,  124,  309,  124,  285,  285,
      285,  124,  317,  124,  310,  174,   81,   91,  124,  313,
      285,  285,  285,  285,  285,  285,  290,  307,  290,  124,
      305,  291,  291,  291,  291,  124,  306,  124,  124,  124,
      311,  124,  312,   91,  314,  289,  124,  315,   82,  320,
      124,  320,  124,  124,  321,  321,  321,  321,  322,  316,
      322,  330,  124,  323,  323,  323,  323,  333,  335,  289,

      291,  291,  291,  291,  291,  291,  291,  291,  124,  124,
      124,  124,  334,  124,  338,  332,  324,  336,  324,  124,
      124,  337,  124,  124,  124,  124,  124,  341,  124,  340,
      339,  324,  352,  354,  343,  360,  324,  342,  321,  321,
      321,  321,  321,  321,  321,  321,  323,  323,  323,  323,
      323,  323,  323,  323,  346,  124,  346,  124,  124,  124,
      356,  124,  347,  356,  347,  353,  124,  124,  124,  346,
      124,  124,  355,  362,  346,  363,  350,  347,  351,  361,
      356,  364,  347,  356,  364,  364,  365,  124,  364,  124,
      365,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   67,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   80,
       80,  124,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   90,   90,  345,   90,   90,  344,   90,   90,
       90,   90,   90,   90,   90,  123,  123,  124,  123,  123,

      158,  124,  124,  158,  124,  158,  158,  158,  158,  158,
      158,  158,  158,  159,  124,  124,  159,  325,  159,  159,
      159,  159,  159,  159,  159,  159,  160,  160,  160,  160,
      160,  160,  325,  160,  160,  160,  160,  160,  160,  163,
      319,  163,  318,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  164,  164,  124,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,   80,   80,  124,  124,   80,
      124,   80,  124,   80,   90,   90,  124,  124,   90,  124,
       90,  283,   90,  189,  189,  189,  198,  198,  199,  199,
      230,  230,  234,  234,  241,  241,  248,  248,  249,  249,

      250,  250,  251,  251,  294,  294,  295,  295,  296,  296,
      297,  297,  326,  326,  327,  327,  328,  328,  329,  329,
      348,  348,  123,  123,  349,  349,  358,  358,  359,  359,
      366,  366,  367,  367,  368,  368,  282,  124,  124,  247,
      247,  240,  240,  232,  231,  125,  161,  161,  124,   91,
      124,  195,  194,  188,  177,  173,  172,  162,  161,  161,
      129,  124,  120,  115,   92,   91,   79,  369,   74,   74,
       15,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369
    } ;

static yyconst flex_int16_t yy_chk[1041] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,   21,    3,    7,    4,    5,    5,    6,
        6,    8,    5,   29,    6,   11,    7,   12,   11,   24,
       12,  363,    8,   13,   13,   29,   13,   14,   14,   22,

       14,   31,   22,   23,   23,   21,   24,   45,   38,   33,
       59,   31,   31,   32,   33,   32,   32,   32,   32,   40,
       40,   49,   33,   38,   43,   38,   38,   50,   43,   51,
       50,   45,   64,   48,   57,   59,   51,   50,  362,   49,
      361,   57,   22,   50,   52,   51,   80,   22,   34,   53,
       34,   34,   34,   34,   48,   54,   43,   52,   56,   52,
       62,   34,   53,   61,   34,   53,   34,   34,   52,   55,
       62,   54,   64,  134,   56,  135,   34,   55,   80,   61,
       90,   58,   34,  135,   55,   60,   82,   82,  134,   60,
       34,   58,   58,   34,   35,  104,   35,   35,   35,   35,

       60,   58,   77,   77,   58,   77,   83,   35,   90,   83,
       35,  130,   35,   81,   81,   81,   81,   60,   81,   91,
       91,  104,   35,  131,  107,  125,  107,  202,   35,   82,
      131,  130,   60,  108,  202,  105,   35,  105,  105,  105,
      105,   99,   99,   99,   99,   81,  113,   81,  105,   83,
      107,  108,   99,   99,   83,   99,  360,  125,  103,  103,
      103,  103,   91,  105,  113,  124,  136,   99,   99,  103,
      103,   81,  103,   99,  106,  110,  106,  114,  132,  106,
      106,  106,  106,  137,  103,  103,  112,  136,  112,  124,
      103,  110,  133,  114,  138,  133,  139,  132,  140,  110,

      141,  114,  137,  142,  144,  145,  147,  152,  146,  184,
      148,  190,  112,  151,  140,  138,  139,  146,  141,  148,
      145,  150,  147,  142,  144,  353,  149,  153,  146,  149,
      151,  155,  150,  184,  154,  190,  148,  169,  153,  152,
      165,  165,  155,  165,  149,  154,  153,  154,  167,  167,
      167,  167,  169,  167,  170,  175,  182,  182,  182,  182,
      201,  203,  200,  201,  175,  175,  226,  170,  170,  178,
      205,  178,  226,  205,  178,  178,  178,  178,  200,  203,
      167,  204,  167,  175,  206,  180,  170,  180,  206,  208,
      180,  180,  180,  180,  189,  183,  183,  183,  183,  210,

      204,  204,  210,  208,  216,  212,  167,  183,  207,  183,
      189,  189,  189,  209,  214,  207,  217,  220,  215,  219,
      209,  212,  183,  214,  218,  216,  219,  183,  189,  215,
      221,  223,  189,  222,  217,  225,  189,  220,  223,  218,
      224,  227,  228,  257,  227,  229,  225,  235,  235,  235,
      235,  221,  233,  222,  257,  228,  224,  253,  229,  229,
      241,  233,  233,  237,  237,  237,  237,  242,  351,  253,
      256,  245,  236,  236,  236,  236,  269,  229,  230,  258,
      233,  241,  345,  269,  236,  243,  236,  243,  242,  245,
      256,  230,  230,  230,  230,  238,  238,  238,  238,  236,

      258,  230,  230,  230,  236,  262,  263,  238,  246,  238,
      230,  243,  259,  230,  230,  230,  230,  230,  230,  234,
      270,  301,  238,  262,  246,  259,  263,  238,  234,  234,
      234,  234,  246,  271,  301,  279,  270,  268,  234,  234,
      234,  266,  279,  274,  271,  284,  280,  234,  267,  274,
      234,  234,  234,  234,  234,  234,  244,  268,  244,  275,
      266,  244,  244,  244,  244,  272,  267,  273,  276,  278,
      272,  340,  273,  284,  275,  288,  300,  276,  280,  286,
      339,  286,  303,  306,  286,  286,  286,  286,  287,  278,
      287,  300,  305,  287,  287,  287,  287,  303,  306,  288,

      290,  290,  290,  290,  291,  291,  291,  291,  302,  310,
      311,  308,  305,  309,  310,  302,  291,  308,  291,  312,
      313,  309,  315,  316,  338,  334,  342,  313,  350,  312,
      311,  291,  334,  342,  316,  350,  291,  315,  320,  320,
      320,  320,  321,  321,  321,  321,  322,  322,  322,  322,
      323,  323,  323,  323,  321,  330,  321,  341,  331,  343,
      344,  352,  323,  344,  323,  341,  337,  354,  355,  321,
      336,  335,  343,  354,  321,  355,  330,  323,  331,  352,
      356,  357,  323,  356,  357,  364,  357,  333,  364,  332,
      364,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  376,
      376,  329,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  377,  377,  319,  377,  377,  318,  377,  377,
      377,  377,  377,  377,  377,  378,  378,  317,  378,  378,

      379,  314,  307,  379,  304,  379,  379,  379,  379,  379,
      379,  379,  379,  380,  299,  298,  380,  293,  380,  380,
      380,  380,  380,  380,  380,  380,  381,  381,  381,  381,
      381,  381,  292,  381,  381,  381,  381,  381,  381,  382,
      283,  382,  282,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  383,  383,  277,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  384,  384,  265,  264,  384,
      261,  384,  260,  384,  385,  385,  255,  254,  385,  252,
      385,  232,  385,  386,  386,  386,  387,  387,  388,  388,
      389,  389,  390,  390,  391,  391,  392,  392,  393,  393,

      394,  394,  395,  395,  396,  396,  397,  397,  398,  398,
      399,  399,  400,  400,  401,  401,  402,  402,  403,  403,
      404,  404,  405,  405,  406,  406,  407,  407,  408,  408,
      409,  409,  410,  410,  411,  411,  231,  213,  211,  193,
      192,  187,  186,  173,  172,  168,  161,  160,  143,  126,
      123,  122,  118,  109,   98,   85,   84,   72,   71,   70,
       47,   42,   39,   36,   28,   25,   20,   15,   10,    9,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"

/*Universal Character Name*/
/*Probablemente quitemos esta cuestion*/
#line 25 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAXLEN 1024
#define PATH "./Pruebas/"
#define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
YY_BUFFER_STATE bp;
#define YY_DECL extern int yylex()

#include "parser2.tab.h"

extern void yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

int line = 1;
int column = 1;
int include_stack_ptr = 0;
int total_includes = 1;
int count_files = 0;
char* actual_token;

struct define_words{
	char name[100];
	char value[1024];	
};

char *files_to_read[100];		//Necesario para el manejo de errores
int lines[100];
int columns[100];
char *curfilename;

int flag_define = 0;
int size_define = 0;
struct define_words record[512];
char *name_def;
char path[128];

void assign_value(char*);

static void commentary(void);
static int check_type(void);
void count_column(void);
#line 871 "lex.yy.c"

#define INITIAL 0
#define INCLUDE_CASE 1
#define INCLUDE_CASE2 2
#define COMMENT 3
#define COMMENT_LINE 4
#define DEFINITION 5
#define DEFINITION_VALUE 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 75 "scanner.l"

#line 1066 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 370 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 971 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "scanner.l"
{commentary();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 "scanner.l"
{BEGIN INITIAL;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 79 "scanner.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 80 "scanner.l"
{printf("Error: Unterminated comment\n");yyterminate();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 82 "scanner.l"
{BEGIN COMMENT_LINE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "scanner.l"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 84 "scanner.l"
{line++;column = 1;BEGIN INITIAL;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "scanner.l"
{ count_column();return(AUTO); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "scanner.l"
{ count_column();return(BREAK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "scanner.l"
{ count_column();return(CASE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "scanner.l"
{ count_column();return(CHAR); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "scanner.l"
{ count_column();return(CONST); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "scanner.l"
{ count_column();return(CONTINUE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "scanner.l"
{ count_column();return(DEFAULT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "scanner.l"
{ count_column();return(DO); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "scanner.l"
{ count_column();return(DOUBLE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "scanner.l"
{ count_column();return(ELSE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "scanner.l"
{ count_column();return(ENUM); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "scanner.l"
{ count_column();return(EXTERN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "scanner.l"
{ count_column();return(FLOAT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "scanner.l"
{ count_column();return(FOR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "scanner.l"
{ count_column();return(GOTO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "scanner.l"
{ count_column();return(IF); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "scanner.l"
{ count_column();return(INT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "scanner.l"
{ count_column();return(LONG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "scanner.l"
{ count_column();return(REGISTER); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "scanner.l"
{ count_column();return(RETURN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "scanner.l"
{ count_column();return(SHORT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "scanner.l"
{ count_column();return(SIGNED); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "scanner.l"
{ count_column();return(SIZEOF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "scanner.l"
{ count_column();return(STATIC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "scanner.l"
{ count_column();return(STRUCT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "scanner.l"
{ count_column();return(SWITCH); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "scanner.l"
{ count_column();return(TYPEDEF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "scanner.l"
{ count_column();return(UNION); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "scanner.l"
{ count_column();return(UNSIGNED); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "scanner.l"
{ count_column();return(VOID); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "scanner.l"
{ count_column();return(VOLATILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "scanner.l"
{ count_column();return(WHILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return I_CONSTANT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return I_CONSTANT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return I_CONSTANT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return I_CONSTANT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 125 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return F_CONSTANT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 126 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return F_CONSTANT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 127 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return F_CONSTANT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return F_CONSTANT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return F_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "scanner.l"
{ yylval.sval = strdup(yytext);count_column();return F_CONSTANT; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 132 "scanner.l"
{yylval.sval = strdup(yytext);count_column();return STRING_LITERAL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 134 "scanner.l"
{ count_column();return ELLIPSIS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 135 "scanner.l"
{ count_column();return RIGHT_ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 136 "scanner.l"
{ count_column();return LEFT_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 137 "scanner.l"
{ count_column();return ADD_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 138 "scanner.l"
{ count_column();return SUB_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 139 "scanner.l"
{ count_column();return MUL_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 140 "scanner.l"
{ count_column();return DIV_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 141 "scanner.l"
{ count_column();return MOD_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 142 "scanner.l"
{ count_column();return AND_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "scanner.l"
{ count_column();return XOR_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 144 "scanner.l"
{ count_column();return OR_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 145 "scanner.l"
{ count_column();return RIGHT_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 146 "scanner.l"
{ count_column();return LEFT_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 147 "scanner.l"
{ count_column();return INC_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 148 "scanner.l"
{ count_column();return DEC_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 149 "scanner.l"
{ count_column();return PTR_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 150 "scanner.l"
{ count_column();return AND_OP; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 151 "scanner.l"
{ count_column();return OR_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 152 "scanner.l"
{ count_column();return LE_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 153 "scanner.l"
{ count_column();return GE_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 154 "scanner.l"
{ count_column();return EQ_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 155 "scanner.l"
{ count_column();return NE_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 156 "scanner.l"
{ count_column();return ';'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 157 "scanner.l"
{ count_column();return '{'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 158 "scanner.l"
{ count_column();return '}'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 159 "scanner.l"
{ count_column();return ','; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 160 "scanner.l"
{ count_column();return ':'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 161 "scanner.l"
{ count_column();return '='; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 162 "scanner.l"
{ count_column();return '('; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 163 "scanner.l"
{ count_column();return ')'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 164 "scanner.l"
{ count_column();return '['; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 165 "scanner.l"
{ count_column();return ']'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 166 "scanner.l"
{ count_column();return '.'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 167 "scanner.l"
{ count_column();return '&'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 168 "scanner.l"
{ count_column();return '!'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 169 "scanner.l"
{ count_column();return '~'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 170 "scanner.l"
{ count_column();return '-'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 171 "scanner.l"
{ count_column();return '+'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 172 "scanner.l"
{ count_column();return '*'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 173 "scanner.l"
{ count_column();return '/'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 174 "scanner.l"
{ count_column();return '%'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 175 "scanner.l"
{ count_column();return '<'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 176 "scanner.l"
{ count_column();return '>'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 177 "scanner.l"
{ count_column();return '^'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 178 "scanner.l"
{ count_column();return '|'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 179 "scanner.l"
{ count_column();return '?'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 181 "scanner.l"
{
											char *result;
											int i = 0;
											result = yytext;
											
											for(i; i < size_define; i++){

												if(strcmp(result, record[i].name) == 0){
													strcpy(result, record[i].value);
													bp = YY_CURRENT_BUFFER;
													YY_BUFFER_STATE n = yy_scan_string(result);
													yy_switch_to_buffer(bp);
													yypush_buffer_state(n);
													files_to_read[total_includes] = "string";
													total_includes++;
													line++;
													break;
												}
											}

											if(i == size_define){
												count_column();
												yylval.sval = strdup(result);
												return check_type();
											}
										}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 208 "scanner.l"
{BEGIN INCLUDE_CASE2;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 210 "scanner.l"
{
								{
									int c;
									while((c = input()) && c != '\n');
								}
								yylineno++;
								/*if(include_stack_ptr >= MAX_INCLUDE_DEPTH){
									fprintf(stderr, "Includes nested too deeply");
									exit(1);
								}*/
								
								strcpy(path,PATH);
								strcat(path, yytext);
								
								
								//include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
								FILE *f = fopen(path,"r");
								if(!f){
									printf("\nInclude file '%s' does not exist\n", yytext);
									line++;
								}
								else{
								//yy_switch_to_buffer(yy_create_buffer ( yyin, YY_BUF_SIZE));
									files_to_read[total_includes++] = path;
									curfilename = path;
									lines[count_files] = line;
									columns[count_files] = column;
									count_files++;
									line = 1;
									column = 1;
									yyin = fopen(path, "r");	
									yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
								}
								BEGIN INITIAL;
							}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 247 "scanner.l"
{BEGIN INCLUDE_CASE;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 249 "scanner.l"
{
								{
									int c;
									while((c = input()) && c != '\n');
								}
								yylineno++;
								/*if(include_stack_ptr >= MAX_INCLUDE_DEPTH){
									fprintf(stderr, "Includes nested too deeply");
									exit(1);
								}*/
								
								strcpy(path,PATH);
								strcat(path, yytext);
								
								
								//include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
								FILE *f = fopen(path,"r");
								if(!f){
									printf("\nInclude file '%s' does not exist\n", yytext);
									line++;
								}
								else{
								//yy_switch_to_buffer(yy_create_buffer ( yyin, YY_BUF_SIZE));
									files_to_read[total_includes++] = path;
									curfilename = path;
									lines[count_files] = line;
									columns[count_files] = column;
									count_files++;
									line = 1;
									column = 1;
									yyin = fopen(path, "r");	
									yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
								}
								BEGIN INITIAL;
							}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 285 "scanner.l"
{BEGIN DEFINITION;}
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 287 "scanner.l"
{
								{
									int c;
									while((c = input()) && c != ' ');
								}
								name_def = yytext;
								BEGIN DEFINITION_VALUE;
							}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 296 "scanner.l"
{
									int i = 0;
									for(i; i < size_define; i++){
										if(strcmp(record[i].name, name_def) == 0){
											strcpy(record[i].value, " ");
											break;
										}
									}

									if(i == size_define){
										strcpy(record[size_define].name, name_def);
										strcpy(record[size_define].value, " ");
										size_define++;
									}
									line ++;
									BEGIN INITIAL;
								}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 314 "scanner.l"
{
								int i = 0;
								for(i; i < size_define; i++){
									if(strcmp(record[i].name, name_def) == 0){
										strcpy(record[i].value, yytext);
										break;
									}
								}

								if(i == size_define){
									strcpy(record[size_define].name, name_def);
									assign_value(yytext);
									size_define++;
								}
								BEGIN INITIAL;
							}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INCLUDE_CASE):
case YY_STATE_EOF(INCLUDE_CASE2):
case YY_STATE_EOF(COMMENT_LINE):
case YY_STATE_EOF(DEFINITION):
case YY_STATE_EOF(DEFINITION_VALUE):
#line 330 "scanner.l"
{
								yypop_buffer_state();
								flag_define = 0;
								int i;
								for(i = total_includes - 1; i > 0; i--){
									
									if(strcmp(files_to_read[i], "string") != 0){
										curfilename = files_to_read[i];
										count_files--;
										line = lines[count_files];
										line += 1;
										column = columns[count_files];
										break;
									}
								}
								total_includes--;
								if(!YY_CURRENT_BUFFER)yyterminate();
								/*if(flag_define){
									flag_define = 0;
									yy_delete_buffer(bp);
								}
								if(--include_stack_ptr < 0){
									yyterminate();
								}
								else{
									--count_files;
									yy_delete_buffer(YY_CURRENT_BUFFER);
									yy_switch_to_buffer(include_stack[include_stack_ptr]);
								}*/
							}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 361 "scanner.l"
{count_column();/*printf(" ");*/}						
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 362 "scanner.l"
{count_column();/*printf("\t");*/}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 363 "scanner.l"
{count_column();/*printf("\n");*/}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 364 "scanner.l"
{count_column();printf("\n%s:%d:%d: Unknown character '%s'\n", files_to_read[total_includes-1],line, column, yytext);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 366 "scanner.l"
ECHO;
	YY_BREAK
#line 1873 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 370 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 370 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 369);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 366 "scanner.l"



/*int main(int argc, char** argv){
	yyin = fopen(argv[1], "r");
	files_to_read[count_files++] = argv[1];
	yylex();
}*/

int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

void count_column(){
	actual_token = yytext;
	for(int i = 0; yytext[i] != '\0'; i++){
		if(yytext[i] == '\n'){
			line ++;
			column = 1;
		}
		
		else if(yytext[i] == '\t') column += 4;
		else column++;	
	}
}

void assign_value(char* value){
	char result_value[1024];
	char temp[512];
	int size_temp = 0;
	strcpy(result_value, "");
	for(int i = 0; i < (int)strlen(value); i++){
	
		if(value[i] == '_' || isalnum(value[i])){
			temp[size_temp] = value[i];
			temp[size_temp+1] = '\0';
			size_temp++;

		}
		else{
			if(size_temp != 0){
				for(int i = 0; i < size_define; i++){

					
					if(strcmp(record[i].name, temp) == 0){
						strcpy(temp, record[i].value);
						i = 0;
					}
				}
				strcat(result_value,temp);
				strcpy(temp, "");
				size_temp = 0;
				i--;
			}
			else{
				int size_result = (int)strlen(result_value);
				result_value[size_result] = value[i];
				result_value[size_result + 1] = '\0';
			}
		}
	}
	if(size_temp != 0){
		
		for(int i = 0; i < size_define; i++){

			if(strcmp(record[i].name, temp) == 0){
				strcpy(temp, record[i].value);
				i = 0;

			}
		}
		strcat(result_value,temp);
		strcpy(temp, "");
		size_temp = 0;
	}
	strcpy(record[size_define].value, result_value);
}

static void commentary(){
	char c, prev = 0;
	while((c = input()) != EOF){
		if(c == '/' && prev == '*')
			return;
		else if(c == '\n'){
			line++;
			column = 1;
		}
		else if(c == '\t'){
			column += 4;
		}
		else {
			column ++;
		}
		prev = c;
	}
	
	printf("Error: Unterminated comment\n");
	exit(1);
}

